version: "3.9"

services:
  app:
    build: .
    image: devops-app
    container_name: devops-app-1
    ports:
      - "8000:5000"
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5000/', timeout=2)"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
  db:
    image: postgres:16
    container_name: devops-db-1
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
